# Generated by Django 4.1.4 on 2023-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_packages', '0002_alter_gympackages_credits_alter_gympackages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gympackages',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gympackages',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
