# Generated by Django 4.1.4 on 2023-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('credits', models.CharField(default='', max_length=10)),
                ('price', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
