# Generated by Django 4.1.4 on 2023-04-12 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(default='', max_length=30)),
                ('class_instructor', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('spot', models.IntegerField(default='')),
                ('spot_name', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('class_id', models.IntegerField(default='')),
                ('user', models.ForeignKey(default='accounts.Account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
