# Generated by Django 4.1.4 on 2023-04-13 04:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address_line',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator(regex='[6,8,9]\\d\\d\\d\\d\\d\\d\\d')]),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
