# Generated by Django 4.1.4 on 2023-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyminstructors',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
